query Autocomplete($inputValue: String!) {
  productSuggestions(fullText: $inputValue, hideUnavailableItems: true)
    @context(provider: "vtex.search-graphql") {
      products {
        items {
          itemId
          name
          images {
            imageUrl
          }
        }
        link
        linkText
      }
    }
}
