query SearchByCategory($categoryId: String) {
  productSearch(category: $categoryId)
    @context(provider: "vtex.store-graphql") {
    products {
      items {
        itemId
        nameComplete
        referenceId {
          Value
        }
      }
    }
  }
}
