query SearchByCategory($selectedFacets: [SelectedFacetInput]) {
  productSearch(selectedFacets: $selectedFacets)
    @context(provider: "vtex.search-graphql") {
    products {
      items {
        itemId
        nameComplete
        sellers {
          sellerId
          sellerName
          sellerDefault
        }
        referenceId {
          Value
        }
      }
    }
  }
}
