query Product($slug: String) {
  product(slug: $slug)
    @context(provider: "vtex.search-graphql") {
      productName
      items {
        itemId
        name
        referenceId {
          Key
          Value
        }
        images {
          imageUrl
        }
      }
    skuSpecifications {
      field {
        name
      }
      values {
        name
      }
    }
  }
}