query Product($slug: String) {
  product(slug: $slug) @context(provider: "vtex.search-graphql") {
    productName
    items {
      itemId
      name
      unitMultiplier
      sellers {
        sellerId
        sellerName
        sellerDefault
        commertialOffer {
          Price
          AvailableQuantity
        }
      }
      referenceId {
        Key
        Value
      }
      images {
        imageUrl
      }
    }
    skuSpecifications {
      field {
        name
      }
      values {
        name
      }
    }
  }
}
