query SearchByCategory($selectedFacets: [SelectedFacetInput]) {
  productSearch(selectedFacets: $selectedFacets, from: 0, to: 90)
    @context(provider: "vtex.search-graphql") {
    products {
      items {
        itemId
        nameComplete
        unitMultiplier
        sellers {
          sellerId
          sellerName
          sellerDefault
        }
        images(quantity: 1) {
          imageUrl
          imageLabel
        }
        referenceId {
          Value
        }
      }
    }
  }
}
