query Products($category: String) {
  products(from: 0, to: 50, category: $category)
    @context(provider: "vtex.search-graphql") {
    brand
    brandId
    cacheId
    categoryId
    productId
    productName
    productReference
    items {
      itemId
      name
      nameComplete
      unitMultiplier
    }
  }
}
