query Product($slug: String) {
  product(slug: $slug) @context(provider: "vtex.search-graphql") {
    productName
    properties {
      name
      values
    }
    items {
      itemId
      name
      unitMultiplier
      sellers {
        sellerId
        sellerName
        sellerDefault
      }
      referenceId {
        Key
        Value
      }
      images {
        imageUrl
      }
    }
    skuSpecifications {
      field {
        name
      }
      values {
        name
      }
    }
  }
}
