query getSkuFromRefIds(
  $refids: [String]
  $orderFormId: String
  $refIdSellerMap: RefIdSellerMap
) {
  skuFromRefIds(
    refids: $refids
    orderFormId: $orderFormId
    refIdSellerMap: $refIdSellerMap
  ) {
    items {
      sku
      refid
      availability
      unitMultiplier
      sellers {
        id
        name
      }
    }
  }
}
