query getSkuFromRefIds($refids: [String], $orderFormId: String) {
  skuFromRefIds(refids: $refids, orderFormId: $orderFormId) {
    items {
      sku
      refid
      availability
      unitMultiplier
      sellers {
        id
        name
      }
    }
  }
}
