query getSkuFromRefIds(
  $refids: [String]
  $orderFormId: String
  $sellerList: [String]
) {
  skuFromRefIds(
    refids: $refids
    orderFormId: $orderFormId
    sellerList: $sellerList
  ) {
    items {
      sku
      refid
      availability
      unitMultiplier
      sellers {
        id
        name
      }
    }
  }
}
